### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by huxuanhao2017** [smallsnail-wh/wh-server#1]
POST http://localhost:8091/wh/oauth/token?username=admin&password=admin&grant_type=password&scope=all 401 (Unauthorized)
登录提示这个，还有什么地方要配置么

**Comment by smallsnail-wh** [comment]
需要数据库配置（表与表数据在wh-server\src\main\resources\createTable中,用户密码为BCrypt加密，用户admin的密码为admin），如果配置了还有错，把后台日志打出来，我看看
